### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-manual#9]
1. On website: https://docs.wise.vote/

![ ](https://user-images.githubusercontent.com/201263/49566263-58e2c780-f92a-11e8-9212-adf7529c4cd8.png)

is:  https://docs.wise.vote/voting-page/
should be: https://wise.vote/voting-page/

2. On website: https://docs.wise.vote/installation

![selection_999 647](https://user-images.githubusercontent.com/201263/49721756-4dadd580-fc63-11e8-9d1a-8cd419da5a3f.png)

is:  https://docs.wise.vote/voting-page/
should be: https://wise.vote/voting-page/

**Comment by Jblew** [comment]
Fixed.
